### ISSUE TITLE
Missing vJoy DLL causes crash at attempting assignment.

### ISSUE THREAD

**Issue by StrScr** [KeyPuncher/WiinUPro#1]
I'm using VS Community 2017 and a Wii U Pro with Windows BT stack. vJoy not installed.
When clicking 'Assign' from the controller button context menu, the program crashes with a missing vJoy DLL error on line 47 of InputsWindow.xaml.cs. Specifically, this is inside the constructor.
`vJoyOffLabel.Visibility = VJoyDirector.Access.Available ? Visibility.Collapsed : Visibility.Visible;`
Here's the details for the exception:
```System.TypeInitializationException occurred
  HResult=0x80131534
  Message=The type initializer for 'WiinUPro.VJoyDirector' threw an exception.

Inner Exception 1:
DllNotFoundException: Unable to load DLL 'vJoyInterface.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```
When trying to solve this by wrapping lines 47-56 in a try-catch block, as well as setting a boolean variable to handle the presence of vJoy to handle lines 64-66, the program still crashes when referencing these now-null properties. Specifically, on line 887, inside the `acceptBtn_Click` event, the program references the null property` _selectedVJoyButtons`. I solved this by wrapping all operations related to vJoy, lines 880-901, inside a conditional that checks if any vJoy properties are null. With this, I am able to assign any non-joystick buttons without the vJoy DLL and the program works as expected!
I am currently trying to adapt the program to optionally work without vJoy being present. Let me know what you think!

**Comment by KeyPuncher** [comment]
Hi, if I am remembering correctly, placing the VJoyInterface.dll for the vJoy\x64 (or the less likely x86) folder into you bin\Debug and bin\Release folders will solve the issue. You shouldn't need vJoy installed, but you'll still need the native vJoy libraries, as they check if vJoy is installed.

**Comment by StrScr** [comment]
Hello there.
I actually found the vJoy folder later on and figured the problem could be solved just by including the DLL. (Hooray!) I just find it a bit strange as to why it's not there by default in the project...
Now that that's solved, I'm setting my sights in solving some other strange problems I've experienced and maybe implementing a few features of my own. This being your project, maybe you can give me an idea of something I could work on?
Cheers.

**Comment by sapajabole** [comment]
Please add ir configuration feature

**Comment by KeyPuncher** [comment]
@StrScr 
Apologies for the (extremely) delayed response. Added the DLL as content and then having it copy to the output folder is simple, but since there are separate DLLs for x64 and x86 builds there should probably be a build script created to automatically choose which to copy with probably defaulting to x64.

There are a bunch of TODO tasks, however, some are probably out dated. Adding functionality to the "Connect As" button would be pretty handy for quickly assigning a controller to an Xbox controller similar to how WiinUSoft does it. And IR calibrations, which is a bit tricky especially to get a good feel from it.
