### ISSUE TITLE
State Change by Holding Not Working?

### ISSUE THREAD

**Issue by jtran2795** [KeyPuncher/WiinUPro#10]
I'm assuming that the feature allowed for the user to hold down a button to temporarily change the state state to another state until the release it.

When I assign a button on my controller to do so, when I hold it down, it shifts to the state, but when I release and try to press something, it stays on the state rather than reverting to the original state.

I'm attempting to do this on a Switch Pro Controller going from states None -> Red -> None.

**Comment by KeyPuncher** [comment]
Looks like this only happens while you are still on the tab for the controller, it keeps the shift state assigned to the one that is selected in the drop down. If you change it back to None, then either minimize WiinUPro or select the Home tab everything functions as normal.

**Comment by KeyPuncher** [comment]
Behavior correction will be included in release 0.9.5.
