### ISSUE TITLE
Add analog joystick support

### ISSUE THREAD

**Issue by creator1372** [KeyPuncher/WiinUPro#11]

**Comment by KeyPuncher** [comment]
For what? I'm assuming the Joy-Cons, which is a much bigger request than it seems since they do not connect to Windows as analog joysticks but rather POV Hats.

**Comment by creator1372** [comment]
because in games like shooters the joycons become VERY imprecise
Because wiinupro only detects joycons

**Comment by KeyPuncher** [comment]
Since this is more of a request, I'm going to close it because I would like to use the Issues in Github to track bugs and not features.
