### ISSUE TITLE
wii remote appears as unrecognised and taiko issue

### ISSUE THREAD

**Issue by devilnouria** [KeyPuncher/WiinUPro#117]
wii remote appears as unrecoinesd when connect 
but when i connect my tatacon taiko to it 
it detects the wii remote and its inputs
but nothing from my taiko drums
one of which just has 2 of the buttons pressed down always and the other pressing over and over again
and my other drum just has two buttons held down and no inputs
but taiko drums work in other games like osu and dolphin wii games
What do?

**Comment by KeyPuncher** [comment]
And your Wii remote is a first party one?
Unfortunately nothing else really comes to mind for this odd behavior.
