### ISSUE TITLE
Calibration issues.

### ISSUE THREAD

**Issue by Neeeere** [KeyPuncher/WiinUPro#126]
I'm trying to calibrate the left stick of my Gamecube Controller. That is connected by a Mayflash adapter, I configure the calibration, even save it and load it, but when I press accept, it just doesn't do a thing, even if I configure calibrate again, it'll be back in default, what may I do?

**Comment by KeyPuncher** [comment]
Game Cube controller via Mayflash adapter? I'm unfamiliar with that adapter. In any case, are you able to find and upload the joystick calibration?
