### ISSUE TITLE
Map multiple xbox controller buttons to one Wii remote button

### ISSUE THREAD

**Issue by Fancy2209** [KeyPuncher/WiinUPro#128]
Hello,
I was using WiinUSoft and I was wondering if there was a way to map Shaking on the Y axis to both Left Stick up and X at the same time. Is it possible or not currently?

**Comment by KeyPuncher** [comment]
Hi, that's not part of WiinUSoft's functionality by design. Cross controller mapping is part of WiinUPro's feature set.

**Comment by Fancy2209** [comment]
> Hi, that's not part of WiinUSoft's functionality by design. Cross controller mapping is part of WiinUPro's feature set.

Ah that's a shame, as what i wanted to do requires motion, who WiinUPro doesn't support currently
