### ISSUE TITLE
Wiinusoft crashes on startup

### ISSUE THREAD

**Issue by realjackatjack** [KeyPuncher/WiinUPro#129]
reacently updated my nividia 3060's drivers to the latested version now whenever i boot up wiinusoft it just crashes, i have tried uninstalling and reinstalling, nothing changes.

**Comment by KeyPuncher** [comment]
I haven't added any exception reporting to WiinUPro either, used to have something like that in WiinUSoft but kept getting too many emails with already resolved issues. What does WiinUSoft do on your machine?
