### ISSUE TITLE
wiinupro 9.2 version rapidfire on controller not working as intended.

### ISSUE THREAD

**Issue by nekoma0** [KeyPuncher/WiinUPro#13]
Button configuration
InputsWindow
Xbox360 - Tab

i would like to report two issues on this window tab.
1.After enable rapidfire button functions on Xbox 360 tabs and save, the next time i opens up the same page trying to tweak or do something, the rapidfire function does not appear to be enable on the page althou the rapidfire kinda works.(sorry as my english is bad and i dont know how to explain this in a short sentence)

2.Rapidfire function not working as intended.
I've tested rapidfire function on InputsWindow, Keyboard and Mouse is working as intended. But Xbox360 is not working as intended.
Behavior report : from what i could see by using a webpage that detects gamepad input. the button seems to be press and hold down for a fixed period no matter what speed i set on the rapidfire xbox 360.

More info on Issue 2(in rough explanation) :
Rapidfire (speed normal) :
press and hold (1 sec), release and wait (1 sec), press and hold(1 sec), release and wait (1 sec), loop

Rapidfire (fast speed) : 
press and hold (1 sec), release and wait (0.5 sec), press and hold (1 sec), release and wait (0.5 sec), loop

rapid fire (very fast) : 
press and hold (1 sec), release and wait (0,1 sec), press and hold (1 sec), release and wait (0.1 sec), loop

conclusion on 2 : speed only affects release and wait ?

**Comment by KeyPuncher** [comment]
Will be part of 0.9.5 release.
