### ISSUE TITLE
Landscape mode for Wheel

### ISSUE THREAD

**Issue by Lornatus** [KeyPuncher/WiinUPro#130]
As far as I can see, there is no landscape mode for Wii controllers to use them as Wheel. Could this please be added?

**Comment by KeyPuncher** [comment]
It doesn't need a separate mode. It doesn't distinguish between its orientations like the Switch Joy-Cons do. Simply set your mappings accordingly. Use the Pitch mappings to configure your wheel turning movements.

**Comment by KeyPuncher** [comment]
I'm glad it's working for you! There was a donate button on the old Google Sites homepage but there's no need. Since I'm not maintaining a domain name anymore and there's no additional controllers I need to purchase, there's currently no expenses in keeping this software available.
