### ISSUE TITLE
Wii U Pro controller recognized by WiinUPro but nothing happens after

### ISSUE THREAD

**Issue by SapphireGaming** [KeyPuncher/WiinUPro#133]
![image](https://github.com/KeyPuncher/WiinUPro/assets/113422857/cfc5109f-cb96-4eab-82bd-6ef3d76403a4)

Trying to connect the controller using the WiinUPro App makes it automatically pop up in the Bluetooth & Devices settings.
Then it says "Driver error" and it does not appear in the "Devices" Tab of the WiinUPro software.

one more image to show how it connects:
![image](https://github.com/KeyPuncher/WiinUPro/assets/113422857/f8261ff8-c3c8-42d4-b310-de8aee236209)

After this, the sync window closes and nothing happens, while the bluetooth & devices settings show "driver error"

**Comment by SapphireGaming** [comment]
HID Drivers have fucked up everything, should work now

**Comment by KeyPuncher** [comment]
Was this unrelated to WiinUPro itself or something external? Wondering if I might need to add an option to skip that driver step.
I haven't done much testing on Windows 11 beyond its early days, and with frequent updates it's impossible for me to keep up.

**Comment by SapphireGaming** [comment]
It was basically this software's drivers not allowing the WiinUPro/WiinUSoft (it affected both) Software drivers to work properly.
https://www.julianloehr.de/educational-work/hid-wiimote/

This software is used for the wii remote only but as I assume it created problems for anything else wii related to connect, removing these drivers (which did not overwrite the wiinupro/wiinusoft drivers) and the app itself fixed the problem however

**Comment by KeyPuncher** [comment]
Oh I see. Makes sense. the only difference between the Wiimotes and Pro is the product id. I have and thoughts about doing something more integrated like this driver which would get rid of the "Dark Souls Problem" but I have a lot to learn about device drivers.
