### ISSUE TITLE
Compile for Android?

### ISSUE THREAD

**Issue by thanone2** [KeyPuncher/WiinUPro#134]
Is it possible for this app to be on android(specifically android 9) without google playstore?

**Comment by KeyPuncher** [comment]
That's tricky, not so much due to the Bluetooth connection but more so for telling Android here's a gaming controller. That's uncharted territory for me.

**Comment by thanone2** [comment]
oh well, thanks for taking the time to answer! although it sparked a little hope!

**Comment by KeyPuncher** [comment]
I would say maybe one day, but I really don't have the time to start another project (or even maintain one for that matter).
