### ISSUE TITLE
WiiU pro controller (clone) reconized as mice

### ISSUE THREAD

**Issue by ducdreamer** [KeyPuncher/WiinUPro#142]
Sorry for my english
I am running windows 10 pro (dutch0
I have installed the latest version of WiiUPro the controller is recognized as Nintendo RVL-CNT-01 under mice keyboard and pen
When i click on ID in the app the controller vibrates
When I press the home button the game bar widgetmenu opens and i can  use the controller but only in this menu
When i press the home buttonagain the game bar widget cose
When press the start(+) buton nothing happens.
What am i doin wrong?

**Comment by ducdreamer** [comment]
I have some additional info
The controller is a clone on the pcb it reads 
ZQDZ-BUTTON-V2.1
EMAIL-790C3966@CC.COM
HTTP://ZHENGQINGDZ1688.COM/
The controller is recognized as a WIIMOTE
could that be the problem?
When i click on the id the controller vibrates
In the windows bluetooth it is connected as Nintendo RVL-CNT-01
The xbox controller is coupled
In WiinUPro the controller is recognized as a wiimote

**Comment by ducdreamer** [comment]
I found the mistake I made when installing the driver.
 I had also installed the bluetooth driver
I have uninstalled everything and made a fresh install unchecked the X box 360 controller
And bluetooth driver in SCP installer
Now everything works OK

**Comment by KeyPuncher** [comment]
Sorry I was unavailable, glad you were able to figure it out though.
