### ISSUE TITLE
Exclusive mode not working + conflict with HIDer

### ISSUE THREAD

**Issue by xBitsoft** [KeyPuncher/WiinUPro#16]
Using combined joycons, exclusive mode doesn't work.

Additionally, when WiinUPro is open and everything connected, launching HIDer (HIDCerberus/HIDGuardian) with WiinUPro whitelisted causes WiinUPro to lose connection to the joycons until manually disconnecting and reconnecting the controllers.

**Comment by KeyPuncher** [comment]
Exclusive mode wasn't designed for the Switch Controllers so that makes sense as to why it wouldn't be working. Also it just doesn't work on Windows 10.
