### ISSUE TITLE
WiinUSoft & WiinPro doesn´t sync properly a new device (Win11)

### ISSUE THREAD

**Issue by TheShinytime** [KeyPuncher/WiinUPro#165]
I switch to a new computer with Win11. I've wanted to use my Wii U Pro controller, but it seems like that in the end of the sync process is an issue. Furthermore, I've tried both programs and installed them with and without Bluetooth driver. It's always the same of two errors:
1. WiinUSoft and WiinPro recognize the controller and sync so that the sync window closes, but the controller won't show up and connection is lost. On Windows, it shows up as an input device which is set up in completed. While pressing a button, it shows up as connected.
![Screenshot 2023-12-29 140040](https://github.com/KeyPuncher/WiinUPro/assets/155164267/319ef7f6-97cc-4800-90e2-0bfefc4e93c1)

2. WiinUSoft and WiinPro won’t recognize the controller, and the sync window stays open. But on Windows, it shows up as an input device with no connection. While pressing a button, it shows up as connected. 
![Screenshot 2023-12-29 155134](https://github.com/KeyPuncher/WiinUPro/assets/155164267/83a2ef05-a4f4-4c84-a060-f97baad24bf0)

It worked only once, but I couldn't reproduce it, and I don't know why. After losing the connection, reconnecting doesn't work.

Additional information about my system:
Windows 11 Pro Version 23H2
OS Build 22631.2861
AMD CPU/GPU 7600/7800xt -> AMD Bluetooth driver

**Comment by NathanGillispie** [comment]
Likewise. I'm using a Wii U Pro controller and WiinUSoft doesn't recognize the device, but it shows up as in input in Windows. Although, windows has never shown the controller as connected.
I'm using Windows 11 Home 22H2 on an Intel bluetooth driver

**Comment by TheShinytime** [comment]
I don't know why, but now it works just fine. I suspect a Windows Defender update or the use of the Direct X repair fix it.
