### ISSUE TITLE
Repeating app error

### ISSUE THREAD

**Issue by insaneTurnip** [KeyPuncher/WiinUPro#17]
![2](https://user-images.githubusercontent.com/5567164/40311779-22d429c8-5d11-11e8-82d9-bc3a0d3f0c83.PNG)
Hello,
This never happened before on any game. I recently re-installed Darksiders II — because I need to finish that game at some point — and I'm getting a new error pop-up every time I alt+tab. Also it's always the same. If I don't click close I can come back to the game and play fine. If I do click it, the game won't recognize my controller anymore, even if I delete it in my bluetooth parameters and pair it again, only solution being to restart my computer (or maybe just the game I admit I haven't tried, silly me).
Thanks.

P.S. : WiinUSoft is just the best, man. I love the WiiU Pro Controller, and the fact there's "finally" a soft that works like a charm, allows pairing them just like we'd do with an x360 and allowing to configure the settings on the fly is just like magic. It runs smooth and is very reactive. The interface is simple AND pretty, it's only got what it needs and that's perfect. Feels fucking good. Love it.

**Comment by insaneTurnip** [comment]
Actually I'm not entirely sure it's the Alt+Tab that makes the bug happen, as I tried doing it once or twice just to test and nothing happened. I'll be giving more informations as I stumble upon them.

**Comment by insaneTurnip** [comment]
Hey, quick update : Alt+tabbing isn't the source of the error, and I have no idea what is. What I do know is that it silently kept stacking until there were 53 pop-ups over 3 hours of playing and the game crashed — 
during a looong wave-based fighting arena, I lost the progress and the loot. 😥
![2](https://user-images.githubusercontent.com/5567164/40401319-1e38cb5e-5e46-11e8-99bd-31db7d5ec06a.PNG)

**Comment by KeyPuncher** [comment]
Thanks for posting this. I wasn't sure if the exception being thrown was still happening or not since I haven't seen it on my machine since an older version.

**Comment by SmokePuddingEveryday** [comment]
Hey, so I get this error a lot too. I think it may have something to do with the Triggers (maybe right) since it seems to happen a lot in games where I use that button alot.

**Comment by insaneTurnip** [comment]
> Hey, so I get this error a lot too. I think it may have something to do with the Triggers (maybe right) since it seems to happen a lot in games where I use that button alot.

Out of curiosity, are you also using SCP Toolkit with PlayStation controllers in parallel, or nothing but WiinUSoft ?

**Comment by SmokePuddingEveryday** [comment]
> > Hey, so I get this error a lot too. I think it may have something to do with the Triggers (maybe right) since it seems to happen a lot in games where I use that button alot.
> 
> Out of curiosity, are you also using SCP Toolkit with PlayStation controllers in parallel, or nothing but WiinUSoft ?

Just WiinUSoft

**Comment by KeyPuncher** [comment]
v3.3 should address this issue.
