### ISSUE TITLE
Major CPU usage when connecting the controllers

### ISSUE THREAD

**Issue by slashiee** [KeyPuncher/WiinUPro#2]
Connecting both my Joycons gives me around 50% CPU usage and adding my Pro Controller to that bumps it up to around 75%.
CPU: Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
Idle:
![image](https://user-images.githubusercontent.com/15317421/28741087-c2c2b158-73c3-11e7-8c77-fe71ebedfadd.png)
1 Joy-Con:
![image](https://user-images.githubusercontent.com/15317421/28741090-cac0c69c-73c3-11e7-8227-0a6d45a077a2.png)
2 Joy-Cons:
![image](https://user-images.githubusercontent.com/15317421/28741092-d02bcfe6-73c3-11e7-824d-fc8f4527c517.png)
2 Joy-Cons + Pro Controller:
![image](https://user-images.githubusercontent.com/15317421/28741096-de04c852-73c3-11e7-85ba-6b85854039e9.png)

**Comment by StrScr** [comment]
Does it only begin when connecting a controller? How long does the high usage last? Is it enough to be bothersome?

**Comment by slashiee** [comment]
The begins when connecting the controller to the program. It lasts until you disconnect the controller from the program. It's bothersome because it can cause the game that you're playing to slow down, especially during emulation.

**Comment by KeyPuncher** [comment]
I have a fix for this. I'm starting the process of getting permission to work on the project. (I also cannot check in or verbally share the fix until then)

**Comment by KeyPuncher** [comment]
Fixed!
