### ISSUE TITLE
My Pro Controller is not Connecting

### ISSUE THREAD

**Issue by Superman321** [KeyPuncher/WiinUPro#21]
I tried to pair this controller: https://www.ebay.com/itm/2-X-Wireless-Schwarz-Joystick-Gamepads-Pro-Controller-Fur-Nintendo-Wii-U-Nov/202510903203
But the controller shows no light and the Controller is on the list but nothing is happening
Is it because its not Original?

**Comment by KeyPuncher** [comment]
That would be correct. Not sure if I replied elsewhere or not but I have not come across any methods to discover third party/imitation controllers via Bluetooth.
