### ISSUE TITLE
Make AutoRefresh work with more than one controller.

### ISSUE THREAD

**Issue by ainmosni** [KeyPuncher/WiinUPro#22]
While setting up a NUC gaming setup on my TV, I found that auto-refresh stops auto-refreshing as soon as soon as there's a controller connected. This was less than ideal for a machine that has normally no keyboard/mouse connected. To solve this issue, I changed the code to keep autorefreshing to 4 and this worked.

Would it be a good idea to make this configurable in the UI, so that people can set how many controllers they have and auto-refresh keeps working until all those are connected?

**Comment by KeyPuncher** [comment]
I did not think of that scenario. Yeah an option in the settings with a number picker sounds like the way to go.

**Comment by ainmosni** [comment]
Honestly, I'd do it myself, but my full Windows development experience consists of changing some numbers and spending an hour trying to figure out how to build this thing. :)
