### ISSUE TITLE
GHWT Drums Support

### ISSUE THREAD

**Issue by PipeRojas** [KeyPuncher/WiinUPro#27]
Im trying to use my GHWT Drums in Clone Hero but WiinUPro says there´s a device named Drums to the Wii Remote put i can´t assign keys to it.

**Comment by KeyPuncher** [comment]
Was working on support for this while working on the Guitar support but the drums were a bit more complex.
What exactly are your expectations for using it? There's data that comes through to signify what is being hit and there's data to sell how hard something was hit.

**Comment by PipeRojas** [comment]
I wanted to use my drums with Clone Hero, but i need to assign drums and cymbals to keyboard keys, i  think thats not needed to capture how hard was the hit

**Comment by PipeRojas** [comment]
Im now using WiitarThing to use my drums, Im closing this issue.
