### ISSUE TITLE
Website broke

### ISSUE THREAD

**Issue by Mercadud** [KeyPuncher/WiinUPro#32]
I tried to go on the wiinupro website, and it says the domain thing has expired, can someone tell the owner that his website thing broke, and make it quick before anyone decides to buy it first and that would suck

**Comment by Dalqin** [comment]
Do you mean http://www.wiinupro.com?

**Comment by Mercaman216** [comment]
Yup, if u open it, it says its expired

**Comment by KeyPuncher** [comment]
Yes, I let it expire. I felt like it wasn't justifiable at the moment with github serving as another home and wiinupro.boards.net and youtube still running. Though looking at analytics it looks like it still gets ~500 hits a day.
It can still be accessed via https://sites.google.com/site/wiinupro/

**Comment by Mercaman216** [comment]
Oh that makes sense, I was just wondering because the website is the first thing that pops on google, so I was thinking about the people who never knew about github

**Comment by LemmusLemmus** [comment]
The new website appears to be broken "Error 404 (Not Found)!!1".
![image](https://user-images.githubusercontent.com/63229554/90015102-65dfbe80-dca8-11ea-8bd2-048799cde8be.png)

**Comment by KeyPuncher** [comment]
I'm not seeing that. It could be that it is still being migrated on Google's end. If it doesn't work in a few days I will contact them.
I really hate the new layout though...

**Comment by KeyPuncher** [comment]
I just discovered GitHub Pages which can serve a static website. I'll eventually create a site and host it that way.

**Comment by Dubidubiduu** [comment]
Where do I find MS_BT_HotFix.zip?

If possible please use redirects for ppl searching some time

**Comment by KeyPuncher** [comment]
Site should be accessible again. Looks like I had to change the access for the published site from restricted to public. I didn't know that was a thing.
