### ISSUE TITLE
Cannot Uninstall Drivers

### ISSUE THREAD

**Issue by Ionicstorm95** [KeyPuncher/WiinUPro#35]
I need to get this off my computer, its interfering with my other controllers and i dont use it anymore. the driver in device manager wont uninstall and i already uninstalled the scp drivers, still causing problems.

**Comment by Ionicstorm95** [comment]
I need to get this off my computer, its interfering with my other controllers and i dont use it anymore. the driver in device manager wont uninstall and i already uninstalled the scp drivers, still causing problems.

**Comment by KeyPuncher** [comment]
What driver are you referring to then if you've already uninstalled the SCP drivers?
WiinUPro does not have any drivers of its own, they are all third party. It includes 3 different drivers in the download. SPC for XInput device emulation, XBox 360 controller drivers for Windows XP, Vista, and 7, and also zdiag for installing drivers for the GCN adpater as per http://m4sv.com/page/wii-u-gcn-usb-driver
