### ISSUE TITLE
How to automatically add emulated XInput devices?

### ISSUE THREAD

**Issue by LemmusLemmus** [KeyPuncher/WiinUPro#36]
I would like to automatically add emulated XInput devices for use with Wiimotes, but I didn't find anywhere to do this from within the program. Looking at the prefs.config file I found that there was an "autoAddXInputDevices" variable. I'd assume that the number decides how many XInput devices to automatically add, but changing the number appears to do nothing.
![image](https://user-images.githubusercontent.com/63229554/90337263-a2315880-dfe1-11ea-8a4f-5c71dc5188f7.png)
Is it possible to automatically add one emulated XInput device for each connected Wiimote through WiinUPro? If so, how?

**Comment by KeyPuncher** [comment]
Hasn't been added yet. The inclusion in the property file appears to be where I started to add it but it's never used in the code. But yes, that is the way it was going to work.
