### ISSUE TITLE
Wii U Pro Controller Not Connecting 

### ISSUE THREAD

**Issue by SoRadGaming** [KeyPuncher/WiinUPro#37]
I do have a fake Wii U Pro Controller, it works on my other pc with a USB Bluetooth dongle and Toshiba Bluetooth stack. Tho I cannot connect it to my laptop with Windows 10 Bluetooth Stack. It pairs is Windows 10, then I refresh WiiUsoft and shows up, but the program freezes and then the controller is gone and disconnected. WiiUSoft 3.4

**Comment by phifogg** [comment]
Same issue for me ... no connection with either WiiUPro nor WiiUSoft

**Comment by foxTr0t1178** [comment]
My controller is connected, the light on the controller shows its connected, and the device shows up on my computer, but it doesn't seem to move my cursor and the buttons don't seem to do anything

**Comment by KeyPuncher** [comment]
Sadly I don't think this controller will ever work with the default Windows stack.
