### ISSUE TITLE
WiinUPro wont add XInput devices

### ISSUE THREAD

**Issue by frigomanu** [KeyPuncher/WiinUPro#38]
As plain as that, i got the controller connected as usual but lately the add button wont do anything. Similar things happen with WiinUsoft. I can't quite point at witch moment this started to happen but I suspect is since I updated Windows 10

**Comment by LemmusLemmus** [comment]
Could you try making sure that the required SCP service drivers are installed on your PC? Without them the add XInput devices button simply does nothing. The SCP drivers can be automatically installed during the installation of WiinUPro/WiinUSoft or be downloaded separately.
I suppose the problem could also be that you already have the maximum of 4 XInput devices connected to your PC, but I find that quite unlikely.

**Comment by frigomanu** [comment]
I reinstaled the software and I now seems to ad Xinput devices just fine. However it seems I can't connect my Wii motion (it synchs fine but whenever I press 'connect' an error pops up saying it's impossible to connect). In reinstalling everything once more

**Comment by LemmusLemmus** [comment]
Exactly what does the error message you get say? Does the error persist after repeated attempts at connecting the wiimote? My guess as to what the problem could possibly be is as follows:
Sometimes the program and Windows are rather slow at connecting the wiimote and the wiimote therefore "gives up" the connection attempt before the program actually finishes connecting, in which case I'd presume the program still thinks that the wiimote is connected, when it actually isn't. Pressing the "connect" button in this case would give the error "Unable to Connect Device". In this case I would just retry the syncing process.
![image](https://user-images.githubusercontent.com/63229554/93739908-bb818200-fbe9-11ea-8813-673a43af30cd.png)
You can make sure that the wiimote is properly connected to Windows before you press the connect button by looking at the four lights on the wiimote. One blue light on the wiimote would indicate that the wiimote is successfully connected. Flashing lights indicates that it is attempting to connect to Windows and all lights off would indicate that the wiimote itself is off and didn't connect. You could also just press the refresh button in the program which would correctly show which devices are and aren't connected to your PC.

**Comment by LemmusLemmus** [comment]
Did you eventually get it to work?

**Comment by frigomanu** [comment]
it did work, I just reinstalled the whole thing and restart the computer and i worked. I could connect my wiimotes and switch pro controller just fine, thanks a lot
