### ISSUE TITLE
WiinUSoft Auto-Connect not working properly

### ISSUE THREAD

**Issue by cheatfreak47** [KeyPuncher/WiinUPro#4]
I set my WiinUSoft to auto-connect my Wii U Pro pad as controller one, but when doing so, it doesn't seem to be accepting inputs until I manually detach and reattach it. 

This is quite annoying as, ideally, I'd just leave wiinusoft running in the background, and let it handle mapping my pad as a 360 controller when I turn it on.

An option to suppress errors when turning the pad off might be useful too.

**Comment by KeyPuncher** [comment]
I've addressed both issues in master.

I just made the connection lost only display as a tray balloon instead of a message box. The message box is a bit invasive for this purpose.

**Comment by cheatfreak47** [comment]
Built the new version myself, and confirmed the issue is fixed, thanks.
