### ISSUE TITLE
Not transforming into controller

### ISSUE THREAD

**Issue by math1474** [KeyPuncher/WiinUPro#43]
So I tried out everything labeled in the steps. except when I get into the part where you it shows your device, and you assert it into a controller slot (1, 2, 3, or 4) it crashes the program saying "lost connection to the controller"

Its been pissing me off for the last few days.
Any ideas?

**Comment by KeyPuncher** [comment]
Officially licensed Nintendo controller? Only thing I can think of is that it might be an imitation controller which tends to have issues. Or a Windows update during that time.
