### ISSUE TITLE
WiinUSoft won't recognize controller after PC shutdown while controller was connected

### ISSUE THREAD

**Issue by rfamartins** [KeyPuncher/WiinUPro#45]
This issue has happened before, but has always fixed itself after a while; if I have my Wii U pro controller connected to WiinUSoft when my computer shuts down (e.g. windows updates, freezes up, or a normal shutdown) when i turn it back on, WiinUSoft is unable to find my controller.

I was using WiinUSoft 3.2.550 and have also tried with its most recent version (WiinUSoft 3.4.592).

Windows is able to find the controller, but unable to pair with it. I am able to pair the controller with my Wii U.

**Comment by rfamartins** [comment]
It started recognizing it again after Windows updated.

**Comment by KeyPuncher** [comment]
WINDOWS UPDATES! _shakes fist_
