### ISSUE TITLE
WiiUSoft Pairs Controller and works for Non-Steam games, but isn't detected by Steam or Steam Games

### ISSUE THREAD

**Issue by Emreld3000** [KeyPuncher/WiinUPro#46]
Current situation (using Windows 10):

Nintendo RVL-CNT-01-UC is  connected and is under "Mouse, Keyboard, & pen."

Xbox 360 Controller for Windows is under"Other Devices. Nothing says if its connected or not.

I can play Fightcade and have it accept inputs.

However, Steam does not. If I go to "General Controller Settings" it tells me there is no controller attached.

What would be the fix for this issue?

**Comment by Wii505** [comment]
It works fine for me. Did you try using the latest version of WiiUSoft and Steam

**Comment by KeyPuncher** [comment]
In steam big picture mode, open settings and go to the controller settings, if you're using Xbox 360 emulation make sure the Xbox configuration option is selected.
