### ISSUE TITLE
Minimize to tray [enhancement]

### ISSUE THREAD

**Issue by Kuki77** [KeyPuncher/WiinUPro#48]
Hi,
Here an enhancement suggestion: How about minimizing to tray instead of normal minimazing?!
Regards
Kuki77

**Comment by LemmusLemmus** [comment]
That is the plan! Good to know that there is interest in such a feature!

**Comment by MoeMonsuta** [comment]
Would Love that feature too. I can finally stop using 4t tray minimizer solo to get the feature.
