### ISSUE TITLE
Shift State Hold

### ISSUE THREAD

**Issue by trei49** [KeyPuncher/WiinUPro#51]
Hi, I have a problem with Hold Shift state - the function works correctly right after I set it, but not after I reload the same profile. The shift state does not go back to None after I stop holding the shift button. 
This issue can be replicated immediately upon connecting the controller and trying to change states while still in the Home tab.
This behavior occurs for all shift colors on any controller button. 

To fix it, I need to go to the controller's tab, then the shift button's assignment window again and simply click Accept without changing anything. 

Shift state on toggle mode works completely fine.

Version downloaded - 0.9.4
Actual version shown in the app - 0.9.616

Is the following save profile config generated correctly for "hold to shift green"? :
{
"input": "ccpHOME",
"collection": [
{
"type": 4,
"keyboardAssignment": null,
"mouseAssignment": null,
"mouseButtonAssignment": null,
"mouseScrollAssignment": null,
"shiftAssignment": {
"TargetState": 3,
"Toggles": false,
"ToggleStates": [],
"Threshold": 0.1
},
"xinputAxisAssignment": null,
"xinputButtonAssignment": null,
"vjoyButtonAssignment": null,
"vjoyAxisAssignment": null,
"vjoyPOVAssignment": null
}

I don't know programming, layman thought is that it feels like either the profile has missing lines in "shiftAssignment" that the app need to process when reloading to recognise shift mode is Hold not Toggle, OR the app doesn't process Toggles-False correctly from saved profiles.

**Comment by KeyPuncher** [comment]
Fixed for 0.9.7.
