### ISSUE TITLE
Wiimote IR to Mouse (50% speed) behaves weirdly

### ISSUE THREAD

**Issue by skybird23333** [KeyPuncher/WiinUPro#56]
When I set the IR sensor to mouse as shown in the image below, it has some weird behaviours. My cursor seems to only go up and horizontally, but it does not go down.
![图片](https://user-images.githubusercontent.com/58811224/113551349-11b68f80-9627-11eb-9d45-7cfdd51481fa.png)

When I bind IR Sensor down to Mouse up and IR Sensor up to nothing, the cursor then goes down.

But if I then set IR Sensor up to Mouse down, the cursor only goes up and not down.

**Comment by LemmusLemmus** [comment]
Fixed since pull request #57!
