### ISSUE TITLE
0.9.7 - default profile crash

### ISSUE THREAD

**Issue by trei49** [KeyPuncher/WiinUPro#60]
Hi there, I have just tried out the new 0.9.7 version released four days ago and it initially worked as expected at first launch until I close the application and re-launch it after setting all my usual preferences, including my default controller profile.

After relaunching the application and upon connecting a controller, the app will immediately crash with the standard windows    "[app] stopped working ..." error message.
In this state, the only way to enable the app to be opened again without crashing is to delete the Config file.

If I do not specify any default profile and manually load one instead, this crash does not occur.

**Comment by KeyPuncher** [comment]
Working on getting a new build. Will close this out when it's ready.

**Comment by thesammy58** [comment]
I see this was closed out but unfortunately it is still impossible to assign a default profile without an immediate crash following the next controller connection. Crossing my fingers a new build will come out some day.
