### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by LemmusLemmus** [KeyPuncher/WiinUPro#62]
Since the WiinUPro website is down it would be very helpful for those new to WiinUPro if there was a README here on GitHub, even a simple one would suffice. The text from the old website could be copied over to the README.

**Comment by validity-check** [comment]
I need help on understanding this library because it might be useful to me. Could you add a description here?

**Comment by yul-oh895** [comment]
I also would like to request this as it would be helpful for anyone that wants to use it for the first time (like myself).

In the meantime, I was able to find the [last snapshot available ](https://web.archive.org/web/20200410102639/http://www.wiinupro.com/)from the Wayback Machine for the website http://www.wiinupro.com. Hopefully this is the same website originally used.

**Comment by KeyPuncher** [comment]
The Google site is still available via [https://sites.google.com/site/wiinupro](https://sites.google.com/site/wiinupro)

Though I still need to make a readme.

**Comment by KeyPuncher** [comment]
Added. Could still use some instructions but it's a start and hopefully helps newcomers.
