### ISSUE TITLE
Undetected after sleep, but still connected to the computer

### ISSUE THREAD

**Issue by Nikolasitude** [KeyPuncher/WiinUPro#63]
Hello everyone, here's the issue.

My wii u pro controller worked fine until my computer slept and it was deconnected.
Now my controller isn't shown in the wiinusoft or wiinupro application, it's also not registered in joy.cpl beside the fact that my computer is connected at my controller as before with bluetooth.
I tried to delete my controller from the bluetooth devices, then I connected it again thanks to wiinusoft (and then wiinupro) but it was still unrecognized by these applications after that.

Thank you

**Comment by rfamartins** [comment]
Same thing happened to me several times: sleeping and shutting down when the controller is connected does this. 
It started working for me again, every single time, when Windows updates.

Started religiously shutting off my controller everytime I have to leave my computer.

**Comment by KeyPuncher** [comment]
I believe I've had this happen to me as well. Seems to be pretty important to disconnect the controller. Unfortunately I don't recall what exactly I did to fix it.

May I suggest opening your device manager and checking to see if the controller is still in there and if so uninstall it then attempt to connect it once again.

Perhaps I can add some code to optionally disconnect controllers when the system is suspended.
[For my own reference https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.powermodechangedeventargs?redirectedfrom=MSDN&view=net-5.0]
