### ISSUE TITLE
Does it works with both Wii remote and nunchuck at same time

### ISSUE THREAD

**Issue by SaiBalaji22** [KeyPuncher/WiinUPro#66]
Hi I’m trying to use both nunchuck and Wii remote at same time. I was able to connect them successfully to my PC and map them with xinput but the problem is when nunchuck is connected to Wii remote only nunchuck works Wii remote does not works similarly if nunchuck is disconnected from Wii remote then Wii remote works. How can I make both to work as a pair because while mapping the controls to Xbox controller both Wii remote and nunchuck together are mapped with Xbox controller input but only one works at a time. How to resolve this so that both Wii remote and nunchuck works at same time

**Comment by pnchrx** [comment]
hi I have the same problem they do not work at the same time

**Comment by LemmusLemmus** [comment]
@pnchrx Well that's not good :/
It could help greatly with troubleshooting if you were to share the information mentioned above.

**Comment by KeyPuncher** [comment]
Resolved with release https://github.com/KeyPuncher/WiinUPro/releases/tag/WiinUSoft3.5
