### ISSUE TITLE
Official WiiU classic controller manufactured by PDP not well recognized

### ISSUE THREAD

**Issue by Shawshank007** [KeyPuncher/WiinUPro#67]
There are 2 kinds of official WiiU Classic controllers : 1 manufactured by PDP (Metal Mario/Samus/Peach/Toad/DonkeyKong fight pad) and 1 manufactured by Hori (Pikachu/Zelda/Mario/Luigi Battle Pad) because Nintendo did not want to invest money himself on classic controller for WiiU. So, Nintendo allowed these 2 manufacturers to build controllers for them (Nintendo seal of quality).

Unfortunately, it seems that the PDP version is not well recognized by WiinUpro as it detects it when connecting its wire to wiimote, but it does not detect key pressed after that.

**Comment by KeyPuncher** [comment]
The controllers on [this page](https://sites.google.com/site/wiinupro/news/thenextsupportedcontrollerpoll) yes?
I did end up getting a Hori pad and that seemed to work fine.
Unfortunate that it seems the PDP Fight pad isn't working, that's pretty odd. So no inputs work at all or just some?

**Comment by Shawshank007** [comment]
Hi KeyPuncher,

your link is not working, but I have 2 unit of this controller :
https://www.amazon.com/PDP-Wired-Fight-Pad-nintendo-u/dp/B00XTY4H3K/ref=sr_1_4?dchild=1&keywords=metal+mario&qid=1625910634&sr=8-4
Amazon.com: PDP Wired Fight Pad for Wii U - Metal Mario: Video Games<https://www.amazon.com/PDP-Wired-Fight-Pad-nintendo-u/dp/B00XTY4H3K/ref=sr_1_4?dchild=1&keywords=metal+mario&qid=1625910634&sr=8-4>
Amazon.com: PDP Wired Fight Pad for Wii U - Metal Mario: Video Games
www.amazon.com

it also exists with different colors : White toad, Brown donkey kong, Blue Samus zero suit, Green Link, Pink peach, ...

I also have 2 unit of the Hori (1 Pikachu and 1 Luigi), and yes, I don't have any issue with the Hori.
With the PDP ones, ALL inputs are NOT working unfortunately.

Best regards,
Shawshank

________________________________
De : KeyPuncher ***@***.***>
Envoyé : jeudi 1 juillet 2021 08:25
À : KeyPuncher/WiinUPro ***@***.***>
Cc : Shawshank007 ***@***.***>; Author ***@***.***>
Objet : Re: [KeyPuncher/WiinUPro] Official WiiU classic controller manufactured by PDP not well recognized (#67)


The controllers on this page<https://sites.google.com/site/wiinupro/news/thenextsupportedcontrollerpoll> yes?
I did end up getting a Hori pad and that seemed to work fine.
Unfortunate that it seems the PDP Fight pad isn't working, that's pretty odd. So no inputs work at all or just some?

**Comment by Shawshank007** [comment]
Hi KeyPuncher,

your link is not working, but I have 2 unit of this controller :
https://www.amazon.com/PDP-Wired-Fight-Pad-nintendo-u/dp/B00XTY4H3K/ref=sr_1_4?dchild=1&keywords=metal+mario&qid=1625910634&sr=8-4

it also exists with different colors : White toad, Brown donkey kong, Blue Samus zero suit, Green Link, Pink peach, ...

I also have 2 unit of the Hori (1 Pikachu and 1 Luigi), and yes, I don't have any issue with the Hori.
With the PDP ones, ALL inputs are NOT working unfortunately.

Best regards,
Shawshank

________________________________
De : KeyPuncher ***@***.***>
Envoyé : jeudi 1 juillet 2021 08:25
À : KeyPuncher/WiinUPro ***@***.***>
Cc : Shawshank007 ***@***.***>; Author ***@***.***>
Objet : Re: [KeyPuncher/WiinUPro] Official WiiU classic controller manufactured by PDP not well recognized (#67)


The controllers on this page<https://sites.google.com/site/wiinupro/news/thenextsupportedcontrollerpoll> yes?
I did end up getting a Hori pad and that seemed to work fine.
Unfortunate that it seems the PDP Fight pad isn't working, that's pretty odd. So no inputs work at all or just some?

**Comment by Shawshank007** [comment]
Hi again,

Finally, I believe that the issue is more with Cemu emulator than in Wiinupro, but I can't be sure of that...

Wiinupro is showing buttons activity until I launch cemu, then wiinupro is no more showing buttons activity.

Regards,
Shawshank

________________________________
De : KeyPuncher ***@***.***>
Envoyé : jeudi 1 juillet 2021 08:25
À : KeyPuncher/WiinUPro ***@***.***>
Cc : Shawshank007 ***@***.***>; Author ***@***.***>
Objet : Re: [KeyPuncher/WiinUPro] Official WiiU classic controller manufactured by PDP not well recognized (#67)


The controllers on this page<https://sites.google.com/site/wiinupro/news/thenextsupportedcontrollerpoll> yes?
I did end up getting a Hori pad and that seemed to work fine.
Unfortunate that it seems the PDP Fight pad isn't working, that's pretty odd. So no inputs work at all or just some?
