### ISSUE TITLE
Program taking WiinUPro input and controller input

### ISSUE THREAD

**Issue by Nerboi** [KeyPuncher/WiinUPro#68]
When trying to use the controller on a game where the pro controller is registered but has the wrong keybinds/doesnt fully work, both wiinupro as well as normal controller inputs are registered.

**Comment by KeyPuncher** [comment]
To clarify, is it the Switch Pro Controller or the Wii U Pro Controller?

**Comment by nupanick** [comment]
I am having this issue with joycons. Steam is getting both the joycon 'generic gamepad' input and the WiinUPro device input, even with 'Exclusive mode' turned on.

**Comment by KeyPuncher** [comment]
> I am having this issue with joycons. Steam is getting both the joycon 'generic gamepad' input and the WiinUPro device input, even with 'Exclusive mode' turned on.

Exclusive mode was built for Windows 7 & earlier for Wii controllers, it does not do anything for Switch controllers right now.
