### ISSUE TITLE
WiinuPro crashing like, a lot.

### ISSUE THREAD

**Issue by cheatfreak47** [KeyPuncher/WiinUPro#7]
I have no idea what I'm doing so wrong to make it crash but just trying to pair a Wii U Pro controller with the sync button and connecting an Xinput pad just immediately crashes the software.

Built from the latest source, using the same SCP driver as usual, under the windows BT stack.

**Comment by cheatfreak47** [comment]
I'd actually really like to start using Wiinupro instead of WiinuSoft by the way, as it seems to be better at properly pairing Wii U Pro Pads, plus I can connect the Xinput Device _before_ pairing a Wii U Pro Controller, which makes it show up in Windows Device Manager _before_ the "wiimote device" entry, which is important because some games (Sonic Heroes) for example, detect controllers based on list order in the "USB Game Controllers" menu.

So, please fix this, thanks. (:

**Comment by Elfinberry** [comment]
I'm having the same issue. It was working fine with the Toshiba Stack, but Windows updated and now when I try it on the windows bluetooth I experience the same issue.

**Comment by cheatfreak47** [comment]
@KeyPuncher It doesn't seem like it, but if you have any ideas for fixes I can definitely try and help test for the problem.

**Comment by KeyPuncher** [comment]
Let's track this issue in the forum since it is possible it is not related to the software itself, at least there is no way to tell without a stack trace.

**Comment by cheatfreak47** [comment]
WiinUPro seems to be crashing _after_ the controller is synced. WiinUPro has no problem syncing the pad it's when it tries to do _anything_ with the pad that it's crashing, so I'm not positive it isn't a software issue.

**Comment by KeyPuncher** [comment]
There could be some external reason as to why this is happening. If I can reproduce the issue or get a stack trace caused by the same symptoms that can be fixed with code then I will reopen the issue.

I'll try to recreate the scenario.
