### ISSUE TITLE
Do i need to Manually reconnect my controller everytime i need to pair it?

### ISSUE THREAD

**Issue by AlastorAlex** [KeyPuncher/WiinUPro#70]
The only way I have managed to get the program to accept my WiiU pro controller is by going to device manager in control panel and manually adding the control, Okay a bit excessive but I can accept it, the program works fine and without complaints, But that alone it works for one session, if I turn off the pc, load the control or even if I turn off the control I must manually perform the control from the control panel and pair it again, is this normal?
I remember that when I used WiiuSoft on my laptop it was automatic, I just had to press Sync and the control appeared to connect. 

maybe i am doing something wrong and i dont khow how to actually turn off the controller correctly, help would be nice.

**Comment by KeyPuncher** [comment]
In WiinUPro there is a button named Sync on the home tab.
In WiinUSoft the button with the red radio wave like icon in the upper left will bring up the sync window.

Use the red sync button on the back of your Wii U controller and wait for it to find it and connect it. This will pair the controller with your computer such that you should only have to press a button on the controller to get it to reconnect unless you pair the controller with something else.

**Comment by AlastorAlex** [comment]
Thanks you for the Response, but sadly The Sync on the WiinUPro Just gives me "Failed to pair", Should i Consider getting another Bluethoot dongle?

**Comment by KeyPuncher** [comment]
Well it's unclear as to what the issue actually is so it's hard for me to advise you one way or another.
The sync button only works with the Microsoft Bluetooth stack, but I can't say for certain that it works on every version of Windows 10 or not.

If you are using a dongle and not a built in, if you have access to another Windows machine to see if that makes a difference or not in order to help see if the dongle is the issue.

**Comment by AlastorAlex** [comment]
I finally managed to get a laptop with bluethoot and IT WORKS FLAWLESSLY, so yeah its my bluethoot dongle (that is a little bit old) i gonna buy a TP-link bluethoot 4.0 adapter and see if that does the trick

**Comment by KeyPuncher** [comment]
Sweet. Now that you mention it, I recall seeing a Bluetooth dongle compatibility list for Wii Remotes. Fairly illusive issue.

**Comment by AlastorAlex** [comment]
YEah it was totally my Bluethoot dongle, Just in case anyone need its, the TP-Link ub400 Wortk FLAWLESS with the app.
