### ISSUE TITLE
Wii and WiiU Controller disconnect after shutdown.

### ISSUE THREAD

**Issue by MrRobWasHere** [KeyPuncher/WiinUPro#75]
Hello, I have been using your software with no problems for quite some time now, but when I tried to connect an additional wii controller it went horribly wrong. It will work, but whenever I close the program/disconnect controllers/turn of controllers, I have to remove them from my Bluetooth devices and manually reconnect them each time. Beforehand, when I was just using a Wii U Pro Controller, I just had to turn it on and open the program and it worked. If there is any way to fix this please tell me.

**Comment by KeyPuncher** [comment]
I will have to see if I can reproduce this behavior, I don't recall it being an issue but it's not in my personal use cases.
Does this affect WiinUPro or WiinUSoft or both?

Please confirm the reproduction steps:
1. Connect a Wii U Pro controller via the Pair option in the software to connect it via MS Bluetooth.
2. Connect a Wii Remote using the same method.
3. Close the program, or Disconnect both controllers, or turn off both controllers.
4. Open the program and observe that they do not re-connect when pressing a button

**Comment by MrRobWasHere** [comment]
Apologies for not saying sooner, but I had fixed this problem awhile ago, I just had to spam buttons for a long time and it would eventually reconnect.

**Comment by KeyPuncher** [comment]
No worries, I tend to have late responses anyway. Thanks for the update!
