### ISSUE TITLE
Xbox Guide button not working

### ISSUE THREAD

**Issue by Erfa** [KeyPuncher/WiinUPro#76]
Hello, I'm using WiinUSoft to use two Wii U Pro controllers as Xbox controllers.

Generally works great! Except that I have never been able to get the Xbox Guide button to work. I've tried mapping other buttons than the default Home button to Xbox guide, but that's not working either.

Unfortunately I don't have a real Xbox controller to test with, so I'm not sure if this problem is unique to WiinUSoft or would apply to any controller. Is this a known issue?

**Comment by LemmusLemmus** [comment]
IIRC for the guide button to work properly you have to disable "open Xbox Game bar using this button on a controller" in Windows settings, see image.
![image](https://user-images.githubusercontent.com/63229554/135841077-e60d2ed4-cc7a-4e02-945c-3a621e9340db.png)

If you want to use your guide button with Steam you might also want to take a look at the Steam controller settings, depending on what you want your guide button to do.

**Comment by Erfa** [comment]
Yes, thank you, that seems to solve it! Sneaky of Microsoft to steal that button by default.
