### ISSUE TITLE
Disabling the deadzone/return to center behavior for the IR sensor

### ISSUE THREAD

**Issue by RavenMacDaddy** [KeyPuncher/WiinUPro#78]
EDIT2: I tried connecting the wiimote to the older version which is WiinUSoft, going through its calibration process and then setting that bounding box size to zero (also confirmed in its prefs.config file), still deadzone behavior.

For reference, this isn't the case with the [Touchmote](http://touchmote.net/) software, however that app instead doesn't extend the range of the emulated analog stick properly on the X axis, so you've a lot of missing range there.

EDIT: At first I thought the issue was the deadzone of the xinput device, however I now notice that it's independent and specifically related to the IR sensor, which can be seen while calibrating it.

I've tried connecting the Wiimote to both the Mayflash DolphinBar and to a normal bluetooth device with a Windows BT stack; TP-Link Archer TX50E to be specific. 

While calibrating, I can change the values of the position of the box and its size, but it doesn't save either by accepting or saving it as a profile or even by choosing that it should be used by default.

Jitter reduction and action while offscreen can't be set either.

In either case, none of that seems to matter because the position gets reset to the center outside of the box anyhow - and looks like a circular deadzone, hence the original assumption of it being related to the xinput deadzone - which can be seen in this attached video where I've even reduced the box size significantly while still in the calibration window.

https://user-images.githubusercontent.com/67732686/140051095-92b27c56-219c-41eb-9139-388a4ab2f177.mp4

It doesn't seem to make any difference whatsoever.

---

Original post:

I'm trying to play with a Wiimote as my Light gun by using DemulShooter combined with WiinUPro.

However, when I set up the IR sensor to act as the left analog stick, there's a built in deadzone which makes it go to the center while I'm trying to aim, and I can't find any way to turn deadzones off.

I haven't found any other github issues or forum posts regarding this which is why I'm posting this.

Does anyone know where this can be turned off?

---

Original second post:

Alright, so I found the options for the Xinput device which shows up in the list, set the deadzones to zero for all axis and where I could also see the corresponding Y and X axis responding to my IR movement and acting smoothy, but if I go to the calibration of the IR sensor I can clearly see how a dead zone is applied like a circle around the middle based on the results.

**Comment by RavenMacDaddy** [comment]
Alright, so I found the options for the Xinput device which shows up in the list, set deadzone to zero for all axes and where I could also see the corresponding Y and X axes responding to my IR movement, but if I go to the calibration of the IR sensor I can clearly see how a dead zone is applied like a circle around the middle based on the results.

In the following video I even set the box to be really small to not interfere with the results.

https://user-images.githubusercontent.com/67732686/140051095-92b27c56-219c-41eb-9139-388a4ab2f177.mp4

**Comment by KeyPuncher** [comment]
The IR sensor feature is incomplete, which is why the action off screen and jitter reduction options are disabled as they have not been implemented.

It does look like the bounding box is broken, setting the width/height to 0 should have disabled it completely. I'll check the logic when the opportunity arises. It shouldn't be a difficult fix.

**Comment by KeyPuncher** [comment]
I found the issue and fixed it locally. It will be available in 0.9.8.

**Comment by VincxBlox** [comment]
I have Wiinupro, trying to use a wii remote as my light gun for jurassic parc. Experiencing the same issue in 0.9.8
Where the setting?
