### ISSUE TITLE
Problem pairing non-official Wii u pro controller

### ISSUE THREAD

**Issue by thakarm** [KeyPuncher/WiinUPro#83]
Hi i just downloaded wiinUSoft and i tried to pair my non-official controller, first via software by the sync button and then via control panel. In both cases my controller is paired but lights are turn off and if i try to set controller as XInput 1 it's not working...
I tried lot of times and don't know ho to do this, can you help me?
Thanks

**Comment by KeyPuncher** [comment]
Hi. I'm not aware of anyone alive who knows how to connect those type of controllers to WIndows' Bluetooth. It's an unsolved mystery.
