### ISSUE TITLE
MS_BT_Hotfix?

### ISSUE THREAD

**Issue by CptButts** [KeyPuncher/WiinUPro#84]
The controller will not stay connected. In the Windows Bluetooth section of the settings, the controller goes from "Connected" back to "Paired" then disappears. I have to go through the sync process again. I'm not able to create the xinput device or press connect, because the program enters a Not Responding state. WiinUSoft did the same thing, but let me create an xinput device that immediately disconnected. Maybe I need the MS BT hotfix? The download for that is completely gone, even on the google site.

**Comment by KeyPuncher** [comment]
Should be [here on google drive](https://drive.google.com/file/d/0B7um5M6gTxX-WXY4M3Y5ck9OQlk/view?usp=sharing&resourcekey=0-OJLb7aAEoAa9C83t5NI_yw). Though it should be completely obsolete with the options that are available in the latest releases.

The issue with connection you're experiencing sounds like the one that occurs seemingly randomly and is typically resolved by syncing the controller to a console.
