### ISSUE TITLE
Virtual Xbox game controller does not recognize keystrokes on wimote when wimote is paired with nunchuck

### ISSUE THREAD

**Issue by Sid0x** [KeyPuncher/WiinUPro#87]
Virtual Xbox game controller does not recognize keystrokes on wimote in WiinUSoft version 3.4 when wimote is paired with nunchuck

**Steps to reproduce:**

1. Connect wiimote(used 2 in 1, with motion plus) to nunchuck
2. Connect wimote to the PC
3. Open WiinUSoft Version 3.4 and in the WiinUSoft window connect wimote as an Xbox Controller (used default config).
4. Open the Windows game controllers (Press Win+r, type joy.cpl, press ok)
5. In the window game controllers select Controller (USB Gamepad Controller) and click on properties, click on the test tab
6. Press any key on wimote and observe the test tab

**Actual result:**
Pressing any key on wimote does not display in the Xbox Controller emulation

**Expected result:**
Pressing a key on wimote is detected and corresponds to pressing a key on the Xbox Controller emulation (according to the config)

**Notes:**
The keystrokes on nunchuck are displayed in the Xbox Controller emulation. WiinUSoft version 3.3 does not have this issue

**Comment by Neelgodly** [comment]
@KeyPuncher this issue is quite burning right now so I think it should be given priority over all others. Fixing this will clear at least 3-4 issues. It has plenty of duplicates

**Comment by Neelgodly** [comment]
Looks like it has been fixed now, great!
