### ISSUE TITLE
Error: No compatable Bluetooth Radios found

### ISSUE THREAD

**Issue by QBart2005** [KeyPuncher/WiinUPro#93]
I wanted to connect my wii u pro controller to my windows 11 pc with bleutooth but I am unable to connect the controller and get this message:

![afbeelding](https://user-images.githubusercontent.com/82606571/157282619-20cbb8bf-5cfd-4cf4-acc5-1515466c31fc.png)

I was wandering if there is an easy fix for this.

I have confirmed that I am using windows BT stacks and I can connect other bleutooth devices with no problem.

**Comment by KeyPuncher** [comment]
Haven't tried on Windows 11 with any real devices yet. I know Windows 11 has made Bluetooth a requirement, so hoping they've added some APIs I can update to.

**Comment by Neelgodly** [comment]
> Haven't tried on Windows 11 with any real devices yet. I know Windows 11 has made Bluetooth a requirement, so hoping they've added some APIs I can update to.

I'm using windows 11 too. My wii remote paired easily and it works flawlessly
