### ISSUE TITLE
WiinUPro seemed to disable my bluetooth

### ISSUE THREAD

**Issue by jvook** [KeyPuncher/WiinUPro#94]
Set up my Wii U pro controller and it was working fine, but then next time I restarted my PC I had no bluetooth radio.  I ran the bluetooth troubleshooter but it says I don't have a bluetooth device.  So I uninstalled WiinUPro and my bluetooth radio came back. Windows 11

**Comment by KeyPuncher** [comment]
WiinUPro itself doesn't do anything with Bluetooth, I'm guessing it is the SCP driver install step. There is a little Bluetooth Driver checkbox in the bottom left corner (if my memory is not failing me) that you should uncheck when installing the SCP driver.

**Comment by MrFunnyman526** [comment]
WiinUPro simply doesn't work. WiinUSoft is vastly superior in terms of connection. Don't even bother with Pro

**Comment by KeyPuncher** [comment]
> WiinUPro simply doesn't work. WiinUSoft is vastly superior in terms of connection. Don't even bother with Pro

I'm not sure where you think you are but this isn't reddit.

**Comment by MrFunnyman526** [comment]
> > WiinUPro simply doesn't work. WiinUSoft is vastly superior in terms of connection. Don't even bother with Pro
> 
> I'm not sure where you think you are but this isn't reddit.

I don't give a fkc about what you think you insect, go fcking kill yourself you miserable piece of shit lmao
