### ISSUE TITLE
WiinUSoft will not notice when i push a button on wii remote

### ISSUE THREAD

**Issue by G43mc** [KeyPuncher/WiinUPro#97]
So I am on Windows 11 and was trying out wiinusoft with my wiimote and the controller has paired but whenever i push a button it doesn't recognize it. Strangely enough my nunchuck is working just not the remote itself

**Comment by G43mc** [comment]
Oh and when I unplug the nunchuck the regular wiimote works

**Comment by KeyPuncher** [comment]
Closed with Release https://github.com/KeyPuncher/WiinUPro/releases/tag/WiinUSoft3.5

**Comment by UlrichFarhadi** [comment]
The website still links to an older version (3.4) of WiinUSoft, i had this error because i downloaded that version from the website, a lot more might do the same and get the same error. Update the link on the website to always show the latest release. Thank you for this wonderful tool btw <3
